// tools/web/paginas/textos.mjs — o que o site diz, nas duas línguas (ADR 0025).
//
// As duas árvores têm de ter a MESMA forma: `conferirParidade` corre na
// construção e chumba se uma chave, um item de lista ou uma linha existir numa
// língua e não na outra. Uma secção que só existe em português é uma página
// inglesa com um buraco que ninguém vê — até alguém a ler.
//
// O que é contado ou medido não está aqui: vem de tools/web/dados.mjs, e entra
// no texto pelos marcadores {assim}. O texto dos povos, das fases e do roteiro
// em português também não: é o do dossiê (§04, §05, §33), lido na construção. O
// que está aqui em inglês para essas tabelas é a tradução, linha a linha, e a
// paridade confere que o número de linhas é o do dossiê.
//
// O inglês é o americano, porque é o do jogo (data/i18n/strings.csv: «Colorblind»,
// «Favor»). O português segue o dossiê: PT-PT, AO90, e o jogador tratado por tu.

export const TEXTOS = {
  pt: {
    lingua: "pt-PT",
    og_locale: "pt_PT",
    caminho: "/",
    meta: {
      titulo: "Empire · um kingdom-builder em pixel art",
      descricao: "Empire é um kingdom-builder 2D em pixel art onde cada império é uma civilização. De dia constróis; à noite, a Podridão chega com uma candeia. Joga-se no browser.",
      og_titulo: "Empire · Cada império é uma civilização",
      og_alt: "O castelo-árvore dos Enramados à noite, com a candeia da Podridão a chegar.",
    },
    nav: {
      rotulo: "Principal", jogo: "O jogo", dia: "Dia e noite", povos: "Povos", controlos: "Como se joga",
      estado: "Estado", dossie: "Dossiê", jogar: "Jogar", menu: "Menu", fechar: "Fechar o menu",
      saltar: "Saltar para o conteúdo", inicio: "Empire, início",
      tema_claro: "Mudar para o tema claro", tema_escuro: "Mudar para o tema escuro",
      outra: { texto: "EN", titulo: "Read in English", lingua: "en" },
    },
    abertura: {
      kicker: ["Greybox jogável", "Godot {godot}", "Nome de trabalho"],
      h1: "Cada império é uma <em>civilização</em>.",
      deck: "Um kingdom-builder 2D em pixel art. De dia, largas moedas para recrutar, construir e subir muralhas. À noite, a Podridão chega pela borda do mundo com uma candeia — e às vezes fala contigo.",
      jogar: "Jogar no browser",
      ver: "Como se joga",
      nota: "Teclado ou comando · Chrome, Edge ou Firefox · cerca de {mb} MB na primeira vez",
      toque: "Neste ecrã tátil o jogo arranca, mas ainda não tem controlos por toque.",
      palco: "O mesmo sítio do jogo ao longo de um dia",
      pausar: "Pausar o dia",
      continuar: "Continuar o dia",
      agora: "Dia {dia} · {fase}",
      alt: "O castelo-árvore dos Enramados na fase «{fase}», fotografado pelo próprio jogo.",
      alt_noite: "O castelo-árvore dos Enramados à noite, com a candeia da Podridão a chegar — três anéis de luz cor de brasa.",
      legenda: "Seis fotografias da build, no mesmo segmento, da alvorada à noite — tiradas pelo próprio jogo no commit {sha7}, a {data}. Os painéis do greybox ficaram fora do recorte.",
      antigas: "O jogo publicado ({publicado}) já não se vê assim: estas imagens são anteriores a ele e voltam a ser tiradas depois da próxima revisão visual.",
    },
    pilares: {
      n: "§04 · O que é",
      h2: "Um reino numa linha, com um andar por cima e outro por baixo.",
      intro: "O Empire joga-se de lado, como o Kingdom — e é o que acontece quando cada região é habitada por gente diferente, a noite tem vontade própria e o chão tem cave. Estes são os cinco pilares do desenho; o que já se joga hoje está mais abaixo, contado.",
      itens: [
        { t: "Cada império é uma civilização", p: "O terreno molda a arquitetura, que molda a economia, que molda a defesa. No fim, o teu império é uma colagem visível de tudo o que absorveste — e lê-se num só ecrã." },
        { t: "Cada súbdito é alguém", p: "O rei gordo de coroa torta, o escudeiro de elmo grande, o ferreiro de bigode. Ninguém tem nome até o merecer, e a morte é permanente." },
        { t: "O mundo tem um andar de baixo", p: "Por baixo do relvado há caves, câmaras e um segundo caminho — para fugir, para flanquear e para esconder o que não se quer à vista." },
        { t: "A lealdade é uma moeda", p: "Inimigos viram aliados e aliados viram inimigos. O bardo encanta, o diplomata assimila, os mercenários vendem-se a quem der mais — e cobram." },
        { t: "A noite é uma personagem", p: "Não há ondas. Há a Podridão: uma mancha que avança pelo terreno, invoca criaturas até chegar às muralhas e recua com o dia. Olhas para o horizonte e sabes quanto tempo tens." },
      ],
    },
    dia: {
      n: "§05 · §80 · O ciclo",
      h2: "Um dia são {dia} segundos. Nunca precisas de olhar para um relógio.",
      intro: "Cada fase tem uma função, um som e uma luz que não se confundem. A noite é castanha, e não azul — e por isso, à noite, o ecrã só tem duas cores que não são terra.",
      segundos: "{s} s",
      tropas: "Tropas",
      rotulo: "As seis fases, à escala da duração",
      fases: {},
      fonte: "Durações do clock.csv, texto do §05. A cor é a da luz de cada fase, calculada como o jogo a calcula.",
    },
    noite: {
      n: "§74 · §75 · §80 · A Podridão",
      h2: "A Podridão ganhou uma candeia, e uma voz.",
      p1: "A partir do {oferta} crepúsculo, a mancha para junto à tua muralha e oferece qualquer coisa — uma pausa, um desvio, uma noite mais leve — por um preço que tens de deixar cair num prato de barro.",
      p2: "Quase todas as ofertas aceites sobem uma dívida que o jogo nunca te mostra como número. Só a luz da candeia a diz — e ela nunca desce.",
      falas: "Fala assim. Nunca ameaça, nunca explica.",
      falas_dia: "a partir do dia {dia}",
      regra: "A regra das duas exceções",
      violeta: "É a Podridão, e só a Podridão.",
      ambar: "É luz — a candeia dela ou uma fogueira tua.",
      terra: "Tudo o resto, à noite, é terra.",
      inst_t: "A candeia, noite a noite",
      inst_dia: "Dia",
      inst_raio: "Raio da luz",
      inst_vel: "Velocidade da mancha",
      inst_massa: "Massa, em campo limpo",
      inst_lados: "Chega por",
      inst_um: "um lado",
      inst_dois: "dois lados",
      inst_teto: "teto",
      inst_px: "px",
      inst_pxs: "px/s",
      inst_desde: "a partir do dia {dia}",
      inst_alt: "A candeia no dia {dia}: três anéis de luz com {raio} px de raio.",
      inst_fonte: "As contas do rot.csv, as mesmas que o jogo faz: três paragens de luz, nunca um gradiente, e um bordo de dither de {dither} px (§80). «px» são píxeis do plano de jogo.",
    },
    povos: {
      n: "§04 · Seis povos",
      h2: "Conquistar não é mais um recurso. É ganhar o direito de construir como eles.",
      intro: "Cada povo é um kit fechado: arquitetura, uma tropa única, uma economia e uma defesa. Duas partidas com a mesma seed jogam-se de forma diferente só pela ordem de conquista.",
      terreno: "Terreno", constroi: "Constrói", economia: "Economia", defesa: "Defesa", tropa: "Tropa única",
      hoje: "É este que se joga hoje",
      nota: "Nomes provisórios. O que é fixo é a lógica de cada um — é dela que saem a arte, as tropas e o balanceamento. Texto do §04.",
      linhas: {},
    },
    controlos: {
      n: "§24 · Como se joga",
      h2: "Dois verbos, e o mundo à volta deles.",
      intro: "Não há menus de construção nem cursores a arrastar. O rei anda de um lado para o outro na linha do solo, e o que ele larga é o que acontece.",
      verbos: [
        { t: "Verbo 1 · Largar", p: "Uma moeda em cima de um vagabundo recruta-o. Em cima de um sítio de obra, constrói. Em cima de um muro, sobe-o um degrau. Segura para largar em contínuo." },
        { t: "Verbo 2 · Passar", p: "Um botão, sempre o mesmo e sempre contextual. Hoje leva o rei de uma faixa para outra — aérea, superfície, subsolo; é também o de montar e o de trocar de personagem, quando isso existir." },
      ],
      tabela: "Os controlos",
      cab: ["Ação", "Teclado e rato", "Comando"],
      acoes: [
        { de: ["move_left", "move_right"], t: "Andar" },
        { de: ["verb_drop"], t: "Largar uma moeda" },
        { de: ["verb_assume"], t: "Usar uma passagem" },
        { de: ["mark_target"], t: "Marcar um alvo" },
        { de: ["king_wheel"], t: "O estado do reino" },
        { de: ["camera_left", "camera_right"], t: "Espreitar para os lados" },
        { de: ["pause"], t: "Pausa e opções" },
      ],
      ou: "ou",
      ecra: "O ecrã no commit {sha7}, a {data}, com os instrumentos do greybox.",
      fonte: "Lido do mapa de entrada do project.godot em cada publicação.",
    },
    estado: {
      n: "Onde está",
      h2: "Um jogo feito à vista, ticket a ticket.",
      intro: "Estes números contam-se de novo a cada publicação, a partir do repositório — nenhum é escrito à mão. Esta versão é do commit {sha}.",
      feitos: "de {total} tickets feitos",
      testes: "testes automáticos",
      adrs: "decisões escritas (ADR)",
      conferidos: "números do dossiê conferidos contra os dados, em cada push",
      barra: "{feitos} tickets feitos, {parciais} parciais e {faltam} por fazer, de {total}",
      quadro: "Os {total} tickets, por trilho",
      quadro_nota: "Os títulos estão em português, como no repositório.",
      feito: "Feito", parcial: "Parcial", falta: "Por fazer",
      leg_feito: "feitos", leg_parcial: "parciais", leg_falta: "por fazer",
      trilhos: {
        F0: "Fase 0 · Fundação", F1: "Fase 1 · Núcleo jogável", F2: "Fase 2 · Fatia vertical", GB: "Greybox", XIII: "Parte XIII · a candeia e a colheita",
        CD: "Conteúdo", ART: "Arte", NB: "Nomes", PUB: "Publicação", AUD: "Auditoria de gameplay",
      },
      lista: "Ver os tickets numa lista",
      cab: ["Ticket", "Título", "Estado"],
      roteiro: "O roteiro: nove fases, cada uma com um critério de saída",
      roteiro_nota: "Do §33. Avança-se quando o critério passa, e não quando parece pronto.",
      em_curso: "{feitos} de {total} tickets",
      por_comecar: "Por começar",
      criterio: "Critério de saída",
      fases: {},
      ler: ["O dossiê inteiro", "O backlog", "As perguntas em aberto", "O código"],
    },
    perguntas: {
      n: "Perguntas",
      h2: "O que costumam perguntar.",
      itens: [
        { q: "Posso jogar já?", r: "Podes: o greybox corre no browser, em <a href=\"/jogar/\">/jogar/</a>. É o jogo a meio — formas lisas, e os sistemas a funcionar por baixo. Joga-se com teclado ou comando; num ecrã tátil arranca, mas ainda não tem controlos." },
        { q: "Quando sai, e onde?", r: "Ainda sem data. O plano é o do §33 — nove fases, com a demo pública na fase {fase_demo} — e o alvo é o Steam, no PC e no Steam Deck (§26)." },
        { q: "Empire é o nome final?", r: "Não. É um nome de trabalho, genérico demais para se encontrar numa pesquisa. O nome final é um ticket (NB-01) e, até lá, não há logótipo." },
        { q: "Em que línguas?", r: "Em {linguas}, desde o primeiro dia: todo o texto do jogo vive numa tabela, com as línguas lado a lado — {chaves} chaves, hoje." },
        { q: "O site ou o jogo recolhem dados?", r: "Não. Sem cookies, sem analytics e sem pedidos a terceiros — até as fontes são servidas daqui. O §32 chama-lhe medir sem espiar: se um dia houver telemetria, é com consentimento explícito e desligada por omissão." },
        { q: "Quem faz isto?", r: "Uma pessoa, com a IA a escrever quase todo o código e o autor a rever. Por isso é que tudo se mede: {testes} testes, {adrs} decisões escritas e um dossiê de {seccoes} secções contra o qual cada linha se revê." },
        { q: "É open source?", r: "O código está à vista, mas não é livre: todos os direitos reservados (<a href=\"{repo}/blob/main/LICENSE\">LICENSE</a>). O Godot e as fontes mantêm as licenças deles." },
      ],
    },
    rodape: {
      jogo: "Jogo", projeto: "Projeto",
      ligacoes_jogo: ["Jogar no browser", "O dossiê", "O código"],
      ligacoes_projeto: ["O backlog", "Perguntas em aberto", "Decisões (ADR)"],
      privacidade: "Sem cookies, sem analytics, sem pedidos a terceiros.",
      direitos: "© {ano} Henrique Passos. Todos os direitos reservados. Empire é um nome de trabalho.",
      versao: "Publicado a {data} · commit {sha} · Godot {godot}",
      godot: "Feito com o Godot Engine (MIT).",
      topo: "Voltar ao topo",
    },
    erro: {
      titulo: "Fora do mapa · Empire",
      h1: "Fora do mapa",
      p: "A região acaba aqui. Uma região tem de terminar em algo (§21) — e esta página não existe.",
      jogar: "Jogar",
      voltar: "Voltar ao início",
    },
    linguas_nome: { pt_PT: "português", en: "inglês" },
    e: "e",
  },

  en: {
    lingua: "en",
    og_locale: "en_US",
    caminho: "/en/",
    meta: {
      titulo: "Empire · a pixel-art kingdom builder",
      descricao: "Empire is a 2D pixel-art kingdom builder where every empire is a civilization. By day you build; by night, the Rot arrives with a lantern. Play it in your browser.",
      og_titulo: "Empire · Every empire is a civilization",
      og_alt: "The Enramados' tree-castle at night, with the Rot's lantern closing in.",
    },
    nav: {
      rotulo: "Main", jogo: "The game", dia: "Day and night", povos: "Peoples", controlos: "How to play",
      estado: "Progress", dossie: "Design doc", jogar: "Play", menu: "Menu", fechar: "Close the menu",
      saltar: "Skip to content", inicio: "Empire, home",
      tema_claro: "Switch to light theme", tema_escuro: "Switch to dark theme",
      outra: { texto: "PT", titulo: "Ler em português", lingua: "pt-PT" },
    },
    abertura: {
      kicker: ["Playable greybox", "Godot {godot}", "Working title"],
      h1: "Every empire is a <em>civilization</em>.",
      deck: "A 2D pixel-art kingdom builder. By day, you drop coins to recruit, build and raise walls. By night, the Rot creeps in from the edge of the world carrying a lantern — and sometimes it talks to you.",
      jogar: "Play in your browser",
      ver: "How to play",
      nota: "Keyboard or gamepad · Chrome, Edge or Firefox · about {mb} MB the first time",
      toque: "On this touch screen the game starts, but it has no touch controls yet.",
      palco: "The same spot in the game over one day",
      pausar: "Pause the day",
      continuar: "Resume the day",
      agora: "Day {dia} · {fase}",
      alt: "The Enramados' tree-castle during {fase}, captured by the game itself.",
      alt_noite: "The Enramados' tree-castle at night, with the Rot's lantern closing in — three rings of ember-colored light.",
      legenda: "Six captures of the build, on the same segment, from dawn to night — taken by the game itself at commit {sha7}, on {data}. The greybox panels were cropped out.",
      antigas: "The published game ({publicado}) no longer looks like this: these images predate it and will be retaken after the next visual review.",
    },
    pilares: {
      n: "§04 · What it is",
      h2: "A kingdom on a line, with a floor above and a floor below.",
      intro: "Empire is played side-on, like Kingdom — and it's what happens when every region is home to different people, the night has a will of its own and the ground has a basement. These are the five pillars of the design; what you can already play is further down, counted.",
      itens: [
        { t: "Every empire is a civilization", p: "Terrain shapes architecture, which shapes the economy, which shapes defense. By the end, your empire is a visible collage of everything you absorbed — readable on a single screen." },
        { t: "Every subject is someone", p: "The fat king with the crooked crown, the squire in the oversized helmet, the mustached smith. Nobody has a name until they earn one, and death is permanent." },
        { t: "The world has a downstairs", p: "Beneath the grass there are cellars, chambers and a second path — to flee, to flank, and to hide what shouldn't be seen." },
        { t: "Loyalty is a currency", p: "Enemies become allies and allies become enemies. The bard charms, the diplomat assimilates, mercenaries sell out to the highest bidder — and they collect." },
        { t: "The night is a character", p: "There are no waves. There is the Rot: a stain that advances across the land, summoning creatures until it reaches your walls, and retreats with the day. You look at the horizon and you know how much time you have." },
      ],
    },
    dia: {
      n: "§05 · §80 · The cycle",
      h2: "A day lasts {dia} seconds. You never need to look at a clock.",
      intro: "Each phase has its own job, sound and light, and none can be mistaken for another. The night is brown, not blue — which is why, at night, the screen has only two colors that aren't earth.",
      segundos: "{s} s",
      tropas: "Troops",
      rotulo: "The six phases, to scale",
      fases: {
        dawn: { pt: "eb0e7fa7", nome: "Dawn", funcao: "The bell rings. The Rot retreats. Losses are counted.", tropas: "Leave their posts" },
        morning: { pt: "396cd3b7", nome: "Morning", funcao: "Recruit, expand, harvest, explore", tropas: "Free work" },
        noon: { pt: "189e7cde", nome: "Noon", funcao: "Enemy fortresses notice you. Risk of a counterattack.", tropas: "Free work" },
        afternoon: { pt: "15b13454", nome: "Afternoon", funcao: "Last window to build. Mercenary prices rise 25%.", tropas: "Free work" },
        dusk: { pt: "027dcd9d", nome: "Dusk", funcao: "The Rot is born at the edge of the map. A warning sounds.", tropas: "Back to their posts" },
        night: { pt: "17150c0c", nome: "Night", funcao: "Defend. Nothing gets built except by the evolved builder.", tropas: "Siege posts" },
      },
      fonte: "Durations from clock.csv, text from §05. Each color is that phase's light, computed the way the game computes it.",
    },
    noite: {
      n: "§74 · §75 · §80 · The Rot",
      h2: "The Rot has a lantern now, and a voice.",
      p1: "From the {oferta} dusk on, the stain stops at your wall and offers something — a pause, a detour, a lighter night — for a price you have to drop onto a clay plate.",
      p2: "Almost every offer you accept raises a debt the game never shows you as a number. Only the lantern's light tells you — and it never goes down.",
      falas: "This is how it talks. It never threatens, it never explains.",
      falas_dia: "from day {dia}",
      regra: "The rule of two exceptions",
      violeta: "It's the Rot, and only the Rot.",
      ambar: "It's light — its lantern or one of your fires.",
      terra: "Everything else, at night, is earth.",
      inst_t: "The lantern, night by night",
      inst_dia: "Day",
      inst_raio: "Light radius",
      inst_vel: "Stain speed",
      inst_massa: "Mass, on open ground",
      inst_lados: "Arrives from",
      inst_um: "one side",
      inst_dois: "both sides",
      inst_teto: "cap",
      inst_px: "px",
      inst_pxs: "px/s",
      inst_desde: "from day {dia}",
      inst_alt: "The lantern on day {dia}: three rings of light, {raio} px in radius.",
      inst_fonte: "The math from rot.csv, the same the game runs: three light stops, never a gradient, and a {dither} px dithered edge (§80). “px” are pixels of the play plane.",
    },
    povos: {
      n: "§04 · Six peoples",
      h2: "Conquest isn't one more resource. It's earning the right to build like them.",
      intro: "Each people is a closed kit: architecture, a unique troop, an economy and a defense. Two runs with the same seed play differently just from the order of conquest.",
      terreno: "Terrain", constroi: "Builds", economia: "Economy", defesa: "Defense", tropa: "Unique troop",
      hoje: "This is the one you play today",
      nota: "Working names. What's fixed is each people's logic — the art, the troops and the balance all come from it. Text from §04.",
      linhas: {
        enramados: { pt: "7c380730", nome: "Enramados", terreno: "Ancient forest", constroi: "In and around giant trees; platforms, ladders, balconies", economia: "Timber and hunting", defesa: "Height: everything shoots from above", tropa: "Canopy archer — fires from the aerial band" },
        portuarios: { pt: "99c6b3f5", nome: "Portuários", terreno: "Coast", constroi: "A huge harbor, piers, warehouses on stilts", economia: "Fishing and trade — the only people who earn coins at night", defesa: "Water as a natural moat", tropa: "Barge — carries 6 troops along the coast" },
        fenda: { pt: "6107e4c0", nome: "Fenda", terreno: "Canyon", constroi: "Carved into the rock, rope bridges between the walls", economia: "Stone and ore", defesa: "Chokepoint: a single way in", tropa: "Counterweight ram" },
        horta: { pt: "e8a22460", nome: "Horta", terreno: "Fertile floodplain", constroi: "Barns, greenhouses, silos, scarecrows", economia: "Farming — twice the yield per plot", defesa: "Numbers: dirt-cheap troops", tropa: "Sower — plants in the middle of combat" },
        fornalha: { pt: "7446a3f9", nome: "Fornalha", terreno: "Volcanic", constroi: "Foundries, chimneys, slag walls", economia: "Metal and weapons", defesa: "Permanent fire on the walls", tropa: "War smith — repairs walls in combat" },
        sobraiz: { pt: "f08333c0", nome: "Sob-Raiz", terreno: "Underground", constroi: "Tunnels, chambers, mushroom farms", economia: "Fungi and secrets", defesa: "No walls — a labyrinth instead", tropa: "Digger — opens passages between bands" },
      },
    },
    controlos: {
      n: "§24 · How to play",
      h2: "Two verbs, and the world around them.",
      intro: "No build menus, no cursors to drag. The king walks back and forth along the ground line, and whatever he drops is what happens.",
      verbos: [
        { t: "Verb 1 · Drop", p: "A coin on a vagrant recruits them. On a building site, it builds. On a wall, it raises it one step. Hold to keep dropping." },
        { t: "Verb 2 · Pass", p: "One button, always the same, always contextual. Today it takes the king from one band to another — aerial, surface, underground; it's also the one for mounting and switching characters, once those exist." },
      ],
      tabela: "The controls",
      cab: ["Action", "Keyboard and mouse", "Gamepad"],
      acoes: [
        { de: ["move_left", "move_right"], t: "Walk" },
        { de: ["verb_drop"], t: "Drop a coin" },
        { de: ["verb_assume"], t: "Use a passage" },
        { de: ["mark_target"], t: "Mark a target" },
        { de: ["king_wheel"], t: "The state of the kingdom" },
        { de: ["camera_left", "camera_right"], t: "Look to the sides" },
        { de: ["pause"], t: "Pause and options" },
      ],
      ou: "or",
      ecra: "The screen at commit {sha7}, on {data}, with the greybox instruments.",
      fonte: "Read from project.godot's input map on every publish.",
    },
    estado: {
      n: "Progress",
      h2: "A game built in the open, one ticket at a time.",
      intro: "These numbers are recounted from the repository on every publish — none is typed by hand. This version is commit {sha}.",
      feitos: "of {total} tickets done",
      testes: "automated tests",
      adrs: "written decisions (ADRs)",
      conferidos: "design-doc numbers checked against the data, on every push",
      barra: "{feitos} tickets done, {parciais} partial and {faltam} to do, out of {total}",
      quadro: "All {total} tickets, by track",
      quadro_nota: "Ticket titles are in Portuguese, as in the repository.",
      feito: "Done", parcial: "Partial", falta: "To do",
      leg_feito: "done", leg_parcial: "partial", leg_falta: "to do",
      trilhos: {
        F0: "Phase 0 · Foundation", F1: "Phase 1 · Playable core", F2: "Phase 2 · Vertical slice", GB: "Greybox", XIII: "Part XIII · the lantern and the harvest",
        CD: "Content", ART: "Art", NB: "Naming", PUB: "Publishing", AUD: "Gameplay audit",
      },
      lista: "See the tickets as a list",
      cab: ["Ticket", "Title", "State"],
      roteiro: "The roadmap: nine phases, each with an exit criterion",
      roteiro_nota: "From §33. You move on when the criterion passes, not when it feels ready.",
      em_curso: "{feitos} of {total} tickets",
      por_comecar: "Not started",
      criterio: "Exit criterion",
      fases: {
        0: { pt: "9fc23862", nome: "Foundation", meses: "1 month", feito: "Repo, CI, CLAUDE.md, bands, camera, GameClock, the scale decision", criterio: "A sprite walks through the three bands and CI is green" },
        1: { pt: "0045a84a", nome: "Playable core", meses: "3 months", feito: "Physical coins, recruiting, walls, archers, the Rot, one night — scenery in flat color blocks, with the characters already animated on top. On Saturdays, the Phase 2 scenery starts (§22).", criterio: "Surviving 10 days is possible and not trivial, and the poster scene is finished" },
        2: { pt: "aef1bd91", nome: "Vertical slice", meses: "3 months", feito: "One complete people with final art (7 buildings, 3 creatures, 5 walls), 1 class, 3 crafts, 1 fortress", criterio: "You play 10 days and want to play the 11th — the test that decides the project" },
        3: { pt: "e531441e", nome: "The second layer", meses: "2 months", feito: "Playable underground, dither reveal, secrets, first journal", criterio: "Minute 10 of §25 works with strangers" },
        4: { pt: "24a99bb7", nome: "Public demo", meses: "2 months", feito: "Tuned onboarding, sound, options, Steam page, web build", criterio: "Page published. Wishlists piling up." },
        5: { pt: "42ab35b2", nome: "Next Fest", meses: "3 months", feito: "Demo at Next Fest, accessibility, Steam Deck, telemetry", criterio: "More than 5,000 wishlists. If not, stop and diagnose." },
        6: { pt: "5d54e36e", nome: "Depth", meses: "6 months", feito: "Classes 2–4, evolutions, mounts, greed, boosts, succession, debt", criterio: "A full 30-day run with no missing systems" },
        7: { pt: "118ec55c", nome: "Content and world", meses: "6 months", feito: "The 6 peoples, procedural generation, 12 journals, chaotic biomes, 2 epilogues", criterio: "Launch. Or Early Access here." },
        8: { pt: "fba7fb95", nome: "Multiplayer", meses: "4 months", feito: "Split screen, then online", criterio: "Post-launch. Cut without regret if needed." },
      },
      ler: ["The whole design doc", "The backlog", "Open questions", "The code"],
    },
    perguntas: {
      n: "Questions",
      h2: "What people usually ask.",
      itens: [
        { q: "Can I play it now?", r: "You can: the greybox runs in your browser, at <a href=\"/jogar/?lingua=en\">/jogar/</a>. It's the game halfway there — flat shapes, with the systems running underneath. Play with a keyboard or a gamepad; on a touch screen it starts, but there are no touch controls yet." },
        { q: "When and where does it come out?", r: "No date yet. The plan is §33's — nine phases, with the public demo in phase {fase_demo} — and the target is Steam, on PC and Steam Deck (§26)." },
        { q: "Is Empire the final name?", r: "No. It's a working title, too generic to find in a search. The final name is a ticket (NB-01), and until then there is no logo." },
        { q: "Which languages?", r: "{linguas}, from day one: every line of text in the game lives in one table, with the languages side by side — {chaves} keys today." },
        { q: "Does the site or the game collect data?", r: "No. No cookies, no analytics and no third-party requests — even the fonts are served from here. §32 calls it measuring without spying: if there's ever telemetry, it will be opt-in and off by default." },
        { q: "Who's making this?", r: "One person, with AI writing almost all the code and the author reviewing it. That's why everything is measured: {testes} tests, {adrs} written decisions and a design doc of {seccoes} sections that every line is reviewed against." },
        { q: "Is it open source?", r: "The code is public but not free: all rights reserved (<a href=\"{repo}/blob/main/LICENSE\">LICENSE</a>). Godot and the fonts keep their own licenses." },
      ],
    },
    rodape: {
      jogo: "Game", projeto: "Project",
      ligacoes_jogo: ["Play in your browser", "The design doc", "The code"],
      ligacoes_projeto: ["The backlog", "Open questions", "Decisions (ADRs)"],
      privacidade: "No cookies, no analytics, no third-party requests.",
      direitos: "© {ano} Henrique Passos. All rights reserved. Empire is a working title.",
      versao: "Published {data} · commit {sha} · Godot {godot}",
      godot: "Made with the Godot Engine (MIT).",
      topo: "Back to top",
    },
    erro: {
      titulo: "Off the map · Empire",
      h1: "Off the map",
      p: "The region ends here. A region has to end in something (§21) — and this page doesn't exist.",
      jogar: "Play",
      voltar: "Back to the start",
    },
    linguas_nome: { pt_PT: "Portuguese", en: "English" },
    e: "and",
  },
};

/** As duas árvores com a mesma forma: as mesmas chaves e o mesmo número de itens. */
export function conferirParidade(a, b, caminho = "") {
  const erros = [];
  const tipo = (x) => (Array.isArray(x) ? "lista" : x === null ? "nulo" : typeof x);
  if (tipo(a) !== tipo(b)) return [`${caminho || "raiz"}: ${tipo(a)} numa língua, ${tipo(b)} na outra`];
  if (Array.isArray(a)) {
    if (a.length !== b.length) erros.push(`${caminho}: ${a.length} itens numa língua, ${b.length} na outra`);
    a.forEach((x, i) => i < b.length && erros.push(...conferirParidade(x, b[i], `${caminho}[${i}]`)));
  } else if (a && typeof a === "object") {
    // As tabelas do dossiê: o português vem do próprio dossiê, e por isso o
    // objecto português está vazio de propósito. Confere-se contra os dados.
    const livres = new Set(["dia.fases", "povos.linhas", "estado.fases"]);
    if (livres.has(caminho)) return erros;
    for (const k of new Set([...Object.keys(a), ...Object.keys(b)])) {
      if (!(k in a) || !(k in b)) erros.push(`${caminho}.${k}: só existe numa língua`);
      else erros.push(...conferirParidade(a[k], b[k], caminho ? `${caminho}.${k}` : k));
    }
  }
  return erros;
}
